In [1]:
import pandas as pd
train = pd.read_csv('./datasets/train.csv')
test = pd.read_csv('./datasets/test.csv')

In [2]:
train.info(

)

<class 'pandas.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   str
 1   HomePlanet    8492 non-null   str
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   str
 4   Destination   8511 non-null   str
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   str
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(2), str(5)
memory usage: 891.5+ KB

In [3]:
train.set_index('PassengerId', inplace=True)
test.set_index('PassengerId', inplace=True)

In [4]:
train.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,8514.000000,8512.000000,8510.000000,8485.000000,8510.000000,8505.000000
mean,28.827930,224.687617,458.077203,173.729169,311.138778,304.854791
std,14.489021,666.717663,1611.489240,604.696458,1136.705535,1145.717189
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,47.000000,76.000000,27.000000,59.000000,46.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

In [5]:
train.head()

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
PassengerId,,,,,,,,,,,,,
0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [6]:
train.columns

Index(['HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age', 'VIP',
       'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'Name',
       'Transported'],
      dtype='str')

In [7]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline

num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler()),
])

cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder())
])

In [8]:
train['Deck'] = train['Cabin'].str[0]
train['Side'] = train['Cabin'].str[-1]
train['Age'] = train['Age'].fillna(train['Age'].median())
train["Group"] = train.index.str.split("_").str[0]
train["GroupSize"] = train["Group"].map(train["Group"].value_counts())


test['Deck'] = test['Cabin'].str[0]
test['Side'] = test['Cabin'].str[-1]
train['Age'] = train['Age'].fillna(train['Age'].median())
test["Group"] = test.index.str.split("_").str[0]
test["GroupSize"] = test["Group"].map(test["Group"].value_counts())

# Create TotalSpend feature
spending_cols = ["RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck"]

train["TotalSpend"] = train[spending_cols].sum(axis=1)
test["TotalSpend"] = test[spending_cols].sum(axis=1)

# Create HasSpending feature
train["HasSpending"] = train["TotalSpend"] > 0
test["HasSpending"] = test["TotalSpend"] > 0

print(train['Group'])

PassengerId
0001_01    0001
0002_01    0002
0003_01    0003
0003_02    0003
0004_01    0004
           ...
9276_01    9276
9278_01    9278
9279_01    9279
9280_01    9280
9280_02    9280
Name: Group, Length: 8693, dtype: str

In [9]:
from sklearn.compose import ColumnTransformer

num_attribs = ['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'GroupSize']
cat_attribs = ['HomePlanet', 'CryoSleep', 'Deck', 'Side', 'Destination', 'VIP', 'HasSpending']

full_pipeline = ColumnTransformer([
    ('num', num_pipeline, num_attribs),
    ('cat', cat_pipeline, cat_attribs),
])

In [10]:
X_train = full_pipeline.fit_transform(train[num_attribs + cat_attribs])
X_test = full_pipeline.transform(test[num_attribs + cat_attribs])
y = train['Transported']

In [11]:
from sklearn.ensemble import RandomForestClassifier

forest_clf = RandomForestClassifier(random_state=42)
forest_clf.fit(X_train, y)

RandomForestClassifier(random_state=42)

In [12]:
from sklearn.model_selection import cross_val_score, StratifiedKFold
forest_scores = cross_val_score(forest_clf, X_train, y, cv=10)
forest_scores.mean()

np.float64(0.783505945531262)

In [13]:
import submit
import importlib
importlib.reload(submit)
forest_pred = forest_clf.predict(X_test)
submit.submit(forest_pred, test.index)

In [14]:
from sklearn.svm import SVC
svm_clf = SVC(random_state=42)
svm_clf.fit(X_train, y)

SVC(random_state=42)

In [15]:
svm_scores = cross_val_score(svm_clf, X_train, y, cv=StratifiedKFold(n_splits=10))
svm_scores.mean()

np.float64(0.7978885758501647)

In [16]:
svm_pred = svm_clf.predict(X_test)
submit.submit(svm_pred, test.index)

In [17]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y)
log_reg_scores = cross_val_score(log_reg, X_train, y, cv=10)
log_reg_scores.mean()

np.float64(0.7911029985582584)

In [18]:
log_pred = log_reg.predict(X_test)
submit.submit(log_pred, test.index)

In [19]:
from sklearn.linear_model import SGDClassifier
sgd_clf = SGDClassifier()
sgd_clf.fit(X_train, y)
sgd_scores = cross_val_score(sgd_clf, X_train, y, cv=10)
sgd_scores.mean()

np.float64(0.7828166871684986)

In [20]:
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier(n_neighbors=11)
knn_clf.fit(X_train, y)
knn_scores = cross_val_score(knn_clf, X_train, y, cv=10)
knn_scores.mean()

np.float64(0.782242106794704)

In [23]:
knn_pred = knn_clf.predict(X_test)
submit.submit(knn_pred, test.index)